(()=>{'use strict';
const S='abbes-maintenance-demo-v1';
const seed=[
{id:'WA-2026-0201',customer:'NordCargo Distribution',location:'Erfurt',asset:'RB-118',type:'Rollenbahn',date:'29.09.2026 · 16:42',issues:0},
{id:'WA-2026-0198',customer:'Muster Logistik GmbH',location:'Eisenach',asset:'TF-031',type:'Teleskopförderer',date:'29.09.2026 · 11:18',issues:1},
{id:'WA-2026-0194',customer:'Parcel Hub Mitte',location:'Kassel',asset:'GF-097',type:'Gurtförderer',date:'28.09.2026 · 17:03',issues:0}
];
const groups=[
['Allgemeiner Zustand',[['clean','Anlage / Umfeld sauber','Keine übermäßige Verschmutzung oder Fremdkörper'],['fixings','Befestigungen & Schraubverbindungen','Keine lockeren oder fehlenden Teile'],['guards','Schutzabdeckungen','Vollständig, fest und unbeschädigt'],['labels','Kennzeichnungen / Warnhinweise','Lesbar und vorhanden']]],
['Fördergurt',[['belt','Gurtzustand','Risse, Schnitte, Ausfransungen und Oberfläche'],['tracking','Bandlauf','Mittiger, ruhiger Lauf ohne Schleifen'],['tension','Gurtspannung','Plausibel und gleichmäßig'],['joints','Gurtverbindung','Verbindung / Verschluss ohne Auffälligkeit']]],
['Antrieb & Lagerung',[['motor','Motor / Getriebe','Geräusche, Erwärmung, sichtbare Leckage'],['drive','Antriebstrommel','Oberfläche, Lauf und Befestigung'],['bearings','Lagerstellen','Geräusch, Spiel und Zustand'],['rollers','Umlenk- / Tragrollen','Freier Lauf und Beschädigungen']]],
['Elektrik & Sicherheit',[['estop','Not-Halt','Funktion und Erreichbarkeit'],['sensors','Sensorik / Lichtschranken','Sitz, Sauberkeit und Funktion'],['cables','Kabel & Leitungen','Keine Quetschungen oder Scheuerstellen'],['switches','Schalter / Bedienelemente','Funktion und Kennzeichnung']]],
['Probelauf',[['noise','Laufgeräusch','Keine auffälligen Geräusche oder Vibrationen'],['function','Funktionsprüfung','Förderbetrieb ohne Störung'],['handover','Anlage betriebsbereit','Nach Wartung sicher übergabefähig']]]
];
const total=groups.reduce((n,g)=>n+g[1].length,0);
const fresh=()=>({customer:'Muster Logistik GmbH',location:'Logistikzentrum Eisenach',order:'WA-2026-0204',asset:'GF-204',type:'Gurtförderer',technician:'Max Mustermann',reason:'Regelmäßige Wartung gemäß Serviceintervall',note:'Anlage nach Wartung funktionsfähig übergeben. Hinweise siehe dokumentierte Mängel.',checks:{},issues:[],confirm:false,signature:''});
const state={step:1,draft:fresh(),protocols:[...seed]};
const $=(q,r=document)=>r.querySelector(q), $$=(q,r=document)=>[...r.querySelectorAll(q)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function load(){try{const x=JSON.parse(localStorage.getItem(S));if(x?.protocols)state.protocols=x.protocols;if(x?.draft)state.draft={...fresh(),...x.draft,checks:x.draft.checks||{},issues:x.draft.issues||[]};}catch{}}
function save(){localStorage.setItem(S,JSON.stringify({protocols:state.protocols,draft:state.draft}));}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2200);}
function view(v){$$('.view').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$$('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.go===v));if(v==='protocols')renderTable();window.scrollTo({top:0,behavior:'smooth'});}
function badge(p){return p.issues?'<span class="badge issue">'+p.issues+' Mangel'+(p.issues>1?'e':'')+'</span>':'<span class="badge done">Abgeschlossen</span>';}
function renderRecent(){const out=state.protocols.slice(0,3).map(p=>'<div class="protocol"><div class="ptype">'+(p.type.includes('Rollen')?'≋':p.type.includes('Teleskop')?'⇥':'⇆')+'</div><div><b>'+esc(p.asset)+' · '+esc(p.type)+'</b><span>'+esc(p.customer)+' · '+esc(p.location)+'</span></div><div class="pmeta">'+esc(p.id)+'<br>'+esc(p.date)+'</div>'+badge(p)+'</div>').join('');$('#recent').innerHTML=out;$('#count').textContent=state.protocols.length;}
function renderTable(q=''){q=q.toLowerCase();const list=state.protocols.filter(p=>(p.id+p.customer+p.location+p.asset+p.type).toLowerCase().includes(q));$('#ptable').innerHTML='<div class="table-head"><span>Auftrag</span><span>Kunde / Standort</span><span>Anlage</span><span>Datum</span><span>Status</span></div>'+list.map(p=>'<div class="trow"><div><b>'+esc(p.id)+'</b></div><div><b>'+esc(p.customer)+'</b><br><span>'+esc(p.location)+'</span></div><div><b>'+esc(p.asset)+'</b><br><span>'+esc(p.type)+'</span></div><span>'+esc(p.date.split(' · ')[0])+'</span><span>'+badge(p)+'</span></div>').join('');}
function openFlow(type='Gurtförderer'){if(state.draft.completed){state.draft=fresh();}state.draft.type=type;syncForm();state.step=1;updateFlow();$('#workflow').classList.add('open');document.body.style.overflow='hidden';}
function closeFlow(){readForm();save();$('#workflow').classList.remove('open');document.body.style.overflow='';}
function syncForm(){const m={customer:'customer',location:'location',order:'order',asset:'asset',type:'type',technician:'tech',reason:'reason',note:'note'};Object.entries(m).forEach(([k,id])=>{const e=$('#'+id);if(e)e.value=state.draft[k]||'';});$('#confirm').checked=!!state.draft.confirm;}
function readForm(){const m={customer:'customer',location:'location',order:'order',asset:'asset',type:'type',technician:'tech',reason:'reason',note:'note'};Object.entries(m).forEach(([k,id])=>{const e=$('#'+id);if(e)state.draft[k]=e.value.trim();});state.draft.confirm=$('#confirm')?.checked||false;}
function updateFlow(){$$('.wfstep').forEach(x=>x.classList.toggle('active',+x.dataset.step===state.step));$$('.step').forEach(x=>{const n=+x.dataset.n;x.classList.toggle('active',n===state.step);x.classList.toggle('complete',n<state.step);$('b',x).textContent=n<state.step?'✓':n;});$('#back').disabled=state.step===1;$('#next').textContent=state.step===1?'Weiter zur Prüfung →':state.step===2?'Weiter zu Mängeln →':state.step===3?'Weiter zum Abschluss →':'Protokoll abschließen & Bericht erstellen ✓';if(state.step===2){readForm();renderChecks();}if(state.step===3)renderIssues();if(state.step===4){renderSummary();setTimeout(drawSavedSignature,30);}save();}
function renderChecks(){$('#sideasset').textContent=state.draft.asset;$('#sidetype').textContent=state.draft.type;$('#sidecustomer').textContent=state.draft.customer;$('#checks').innerHTML=groups.map(g=>'<section class="checksec"><h3>'+g[0]+'</h3>'+g[1].map(i=>{const s=state.draft.checks[i[0]]||'';return '<div class="checkrow"><div><b>'+i[1]+'</b><small>'+i[2]+'</small></div><div class="statuses" data-id="'+i[0]+'"><button data-s="ok" class="'+(s==='ok'?'sel':'')+'">✓ OK</button><button data-s="bad" class="'+(s==='bad'?'sel':'')+'">! Mangel</button><button data-s="na" class="'+(s==='na'?'sel':'')+'">– N/A</button></div></div>';}).join('')+'</section>').join('');$$('.statuses button').forEach(b=>b.onclick=()=>setCheck(b.parentElement.dataset.id,b.dataset.s));progress();}
function meta(id){for(const g of groups)for(const i of g[1])if(i[0]===id)return i;}
function setCheck(id,s){state.draft.checks[id]=s;const row=$('.statuses[data-id="'+id+'"]');$$('button',row).forEach(b=>b.classList.toggle('sel',b.dataset.s===s));const m=meta(id);if(s==='bad'&&!state.draft.issues.some(x=>x.check===id))state.draft.issues.push({id:'i'+Date.now()+Math.random(),check:id,title:m[1],desc:'Auffälligkeit am Prüfpunkt „'+m[1]+'“ festgestellt.',action:'',priority:'Hinweis',photo:''});if(s!=='bad')state.draft.issues=state.draft.issues.filter(x=>x.check!==id);progress();save();}
function progress(){const n=Object.values(state.draft.checks).filter(Boolean).length;$('#progressText').textContent=n+' / '+total;$('#progressBar').style.width=Math.round(n/total*100)+'%';}
function renderIssues(){const a=state.draft.issues;$('#issuecount').textContent=a.length+' Mangel'+(a.length===1?'':'e');if(!a.length){$('#issues').innerHTML='<div class="empty"><b>✓ Keine Mängel dokumentiert</b>Du kannst unten trotzdem eine zusätzliche Auffälligkeit erfassen.</div>';return;}$('#issues').innerHTML=a.map((x,n)=>'<article class="issue" data-id="'+x.id+'"><div class="issuehead"><div><b>'+String(n+1).padStart(2,'0')+' · '+esc(x.title)+'</b></div><button class="remove">×</button></div><div class="issuegrid"><label><span>Beschreibung</span><textarea data-f="desc" placeholder="Was wurde festgestellt? (optional)">'+esc(x.desc)+'</textarea></label><label><span>Maßnahme / Empfehlung</span><textarea data-f="action" placeholder="Was wurde gemacht / empfohlen?">'+esc(x.action)+'</textarea><span style="margin-top:8px">Priorität</span><select data-f="priority"><option'+(x.priority==='Hinweis'?' selected':'')+'>Hinweis</option><option'+(x.priority==='Bald beheben'?' selected':'')+'>Bald beheben</option><option'+(x.priority==='Kritisch'?' selected':'')+'>Kritisch</option></select><span style="margin-top:8px">Foto</span><div class="photo">'+(x.photo?'<img src="'+x.photo+'" alt="Mängelfoto">':'<span>＋ Foto aufnehmen / wählen</span>')+'<input type="file" accept="image/*" capture="environment"></div></label></div></article>').join('');$$('.issue').forEach(card=>{const x=a.find(i=>i.id===card.dataset.id);$('.remove',card).onclick=()=>{state.draft.issues=state.draft.issues.filter(i=>i.id!==x.id);if(x.check)state.draft.checks[x.check]='';renderIssues();save();};$$('[data-f]',card).forEach(e=>e.oninput=()=>{x[e.dataset.f]=e.value;save();});$('input[type=file]',card).onchange=e=>photo(e,x);});}
function photo(e,x){const f=e.target.files?.[0];if(!f)return;if(f.size>4*1024*1024){toast('Demo: Bitte Bild unter 4 MB wählen.');return;}const r=new FileReader();r.onload=()=>{x.photo=r.result;renderIssues();save();toast('Foto lokal gespeichert.');};r.readAsDataURL(f);}
function renderSummary(){readForm();const v=Object.values(state.draft.checks);$('#sumtitle').textContent=state.draft.asset+' · '+state.draft.type;$('#summeta').textContent=state.draft.customer+' · '+state.draft.location;$('#sumok').textContent=v.filter(x=>x==='ok').length;$('#sumbad').textContent=v.filter(x=>x==='bad').length;$('#sumna').textContent=v.filter(x=>x==='na').length;}
function validate(){readForm();if(state.step===1&&(!state.draft.customer||!state.draft.location||!state.draft.order||!state.draft.asset)){toast('Bitte Pflichtfelder ausfüllen.');return false;}if(state.step===2){const n=Object.values(state.draft.checks).filter(Boolean).length;if(n<total){toast('Noch '+(total-n)+' Prüfpunkte offen.');return false;}}return true;}
function next(){if(!validate())return;if(state.step<4){state.step++;updateFlow();$('.wf-content').scrollTo({top:0,behavior:'smooth'});}else finish();}
function finish(){readForm();
state.draft.issues=state.draft.issues.filter(x=>x.check||x.desc.trim()||x.action.trim()||x.photo);
state.draft.issues.forEach(x=>{if(!x.desc.trim())x.desc=x.check?'Auffälligkeit am Prüfpunkt „'+x.title+'“ festgestellt.':'Zusätzliche Auffälligkeit dokumentiert.';});
const p={id:state.draft.order,customer:state.draft.customer,location:state.draft.location,asset:state.draft.asset,type:state.draft.type,date:new Date().toLocaleDateString('de-DE')+' · '+new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'}),issues:state.draft.issues.length,details:JSON.parse(JSON.stringify(state.draft))};
state.protocols=[p,...state.protocols.filter(x=>x.id!==p.id)];state.draft.completed=true;
renderReport();renderRecent();save();closeFlow();$('#reportoverlay').classList.add('open');document.body.style.overflow='hidden';toast('Protokoll erfolgreich abgeschlossen und lokal gespeichert.');}
function renderReport(){const d=state.draft,v=Object.values(d.checks),ok=v.filter(x=>x==='ok').length,bad=v.filter(x=>x==='bad').length,na=v.filter(x=>x==='na').length;const checkhtml=groups.map(g=>'<div class="rsection"><h2>'+g[0]+'</h2>'+g[1].map(i=>{const s=d.checks[i[0]]||'na',map={ok:['OK','rok'],bad:['Mangel','rbad'],na:['N/A','rna']},m=map[s];return '<div class="rcheck"><span>'+i[1]+'</span><span class="'+m[1]+'">'+m[0]+'</span></div>';}).join('')+'</div>').join('');const issues=d.issues.length?d.issues.map((x,n)=>'<div class="rissue"><b>'+String(n+1).padStart(2,'0')+' · '+esc(x.title)+' · '+esc(x.priority)+'</b><p>'+esc(x.desc)+'</p>'+(x.action?'<p><strong>Maßnahme:</strong> '+esc(x.action)+'</p>':'')+'</div>').join(''):'<p style="font-size:8px;color:#758091">Keine Mängel dokumentiert.</p>';$('#report').innerHTML='<div class="rhead"><div class="rlogo"><span class="mark" style="width:31px;height:31px"></span><div><b>ABBES</b><small>Digital · Konzeptdemo</small></div></div><div class="rtitle"><h1>Wartungsprotokoll</h1><span>'+esc(d.order)+'</span></div></div><div class="rinfo"><div class="rf"><span>Kunde</span><b>'+esc(d.customer)+'</b></div><div class="rf"><span>Standort</span><b>'+esc(d.location)+'</b></div><div class="rf"><span>Anlage</span><b>'+esc(d.asset)+' · '+esc(d.type)+'</b></div><div class="rf"><span>Monteur</span><b>'+esc(d.technician)+'</b></div><div class="rf"><span>Anlass</span><b>'+esc(d.reason)+'</b></div><div class="rf"><span>Datum</span><b>'+new Date().toLocaleDateString('de-DE')+'</b></div></div><div class="rnums"><div><strong>'+ok+'</strong><span>Prüfpunkte OK</span></div><div><strong>'+bad+'</strong><span>Mängel</span></div><div><strong>'+na+'</strong><span>N/A</span></div></div>'+checkhtml+'<div class="rsection"><h2>Festgestellte Mängel / Maßnahmen</h2>'+issues+'</div><div class="rsection"><h2>Abschließende Bemerkung</h2><div style="background:#f5f7f9;padding:10px;border-radius:8px;font-size:8px">'+esc(d.note||'–')+'</div></div><div class="rsign"><div class="sigline">'+(d.signature?'<img class="sigimg" src="'+d.signature+'" alt="Unterschrift">':'')+'Monteur · '+esc(d.technician)+'</div><div class="sigline">Kunde / Ansprechpartner '+(d.confirm?'· informiert':'· Demo ohne Gegenzeichnung')+'</div></div><div class="rfoot"><span>Digital erstellt · Konzeptdemo von ABBES</span><span>Unverbindliche ABBES-Konzeptdemo</span></div>';$('#reportnum').textContent=d.order;}
function scan(){const p=[['GF-204','Gurtförderer'],['RB-118','Rollenbahn'],['TF-031','Teleskopförderer']][Math.floor(Math.random()*3)];state.draft.asset=p[0];state.draft.type=p[1];syncForm();toast(p[0]+' erkannt · '+p[1]);}
function connection(){const on=navigator.onLine;$('#online').classList.toggle('offline',!on);$('#online b').textContent=on?'Online':'Offline';$('#syncb').textContent=on?'Bereit':'Offline-Modus';$('#syncs').textContent=on?'Daten lokal gespeichert':'Weiterarbeiten möglich';if(!on)toast('Offline-Modus aktiv – weiterarbeiten möglich.');}
let ctx,drawing=false,last;
function sigSetup(){const c=$('#sig');ctx=c.getContext('2d');const pos=e=>{const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height};};c.onpointerdown=e=>{drawing=true;last=pos(e);c.setPointerCapture(e.pointerId);$('#sigtext').style.display='none';};c.onpointermove=e=>{if(!drawing)return;const p=pos(e);ctx.strokeStyle='#101a3a';ctx.lineWidth=4;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p;};c.onpointerup=()=>{if(!drawing)return;drawing=false;state.draft.signature=c.toDataURL();save();};$('#clearsig').onclick=()=>{ctx.clearRect(0,0,c.width,c.height);state.draft.signature='';$('#sigtext').style.display='';save();};}
function drawSavedSignature(){const c=$('#sig');ctx.clearRect(0,0,c.width,c.height);if(!state.draft.signature){$('#sigtext').style.display='';return;}const im=new Image();im.onload=()=>ctx.drawImage(im,0,0,c.width,c.height);im.src=state.draft.signature;$('#sigtext').style.display='none';}
load();renderRecent();renderTable();syncForm();sigSetup();connection();
$$('[data-go]').forEach(b=>b.onclick=()=>view(b.dataset.go));$$('[data-template]').forEach(b=>b.onclick=()=>openFlow(b.dataset.template));$('#start').onclick=()=>openFlow('Gurtförderer');$('#scanstart').onclick=()=>{openFlow('Gurtförderer');setTimeout(scan,180)};$('#scan').onclick=scan;$('#closeflow').onclick=closeFlow;$('#next').onclick=next;$('#back').onclick=()=>{if(state.step>1){state.step--;updateFlow();}};$('#allok').onclick=()=>{groups.forEach(g=>g[1].forEach(i=>{if(state.draft.checks[i[0]]!=='bad')state.draft.checks[i[0]]='ok';}));renderChecks();save();toast('Offene Prüfpunkte auf OK gesetzt.');};$('#addissue').onclick=()=>{state.draft.issues.push({id:'m'+Date.now(),check:null,title:'Zusätzliche Auffälligkeit',desc:'',action:'',priority:'Hinweis',photo:''});renderIssues();save();};$('#search').oninput=e=>renderTable(e.target.value);$('#confirm').onchange=e=>{state.draft.confirm=e.target.checked;save();};$('#closeReport').onclick=()=>{$('#reportoverlay').classList.remove('open');document.body.style.overflow='';};$('#print').onclick=()=>window.print();$('#reset').onclick=()=>{if(confirm('Demo-Daten auf Ausgangszustand zurücksetzen?')){localStorage.removeItem(S);state.protocols=[...seed];state.draft=fresh();renderRecent();renderTable();syncForm();toast('Demo zurückgesetzt.');}};$$('#workflow input,#workflow select,#workflow textarea').forEach(e=>e.addEventListener('change',()=>{readForm();save();}));addEventListener('online',connection);addEventListener('offline',connection);if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
})();