(()=>{const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s)),toast=$('[data-toast]');let tt;function note(m){if(!toast)return;toast.textContent=m;toast.classList.add('show');clearTimeout(tt);tt=setTimeout(()=>toast.classList.remove('show'),2300)}
const menu=$('.menu'),nav=$('#nav');if(menu&&nav){menu.addEventListener('click',()=>{const o=!nav.classList.contains('open');nav.classList.toggle('open',o);menu.setAttribute('aria-expanded',String(o))});$$('a',nav).forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}))}
let issue='';$$('[data-service]').forEach(a=>a.addEventListener('click',()=>{issue=a.dataset.service||'';$$('.issues button').forEach(b=>b.classList.toggle('active',b.dataset.value===issue))}));
const form=$('[data-booking-form]');if(form){const steps=$$('[data-step]',form),bar=$$('.steps span'),err=$('[data-booking-error]');let step=0;function show(n){step=Math.max(0,Math.min(n,steps.length-1));steps.forEach((x,i)=>x.hidden=i!==step);bar.forEach((x,i)=>x.classList.toggle('on',i<=Math.min(step,3)))}function valid(){let ok=true;$$('[required]',steps[step]).forEach(x=>{if(!x.checkValidity()){x.reportValidity();ok=false}});if(step===1&&!issue){note('Bitte ein Anliegen auswählen.');ok=false}return ok}
$$('.issues button').forEach(b=>b.addEventListener('click',()=>{issue=b.dataset.value||b.textContent.trim();$$('.issues button').forEach(x=>x.classList.toggle('active',x===b))}));$$('[data-next]',form).forEach(b=>b.addEventListener('click',()=>{if(valid())show(step+1)}));$$('[data-back]',form).forEach(b=>b.addEventListener('click',()=>show(step-1)));
form.addEventListener('submit',e=>{e.preventDefault();if(!valid()){if(err)err.textContent='Bitte prüfen Sie die Pflichtfelder.';return}if(err)err.textContent='';const d=new FormData(form),vehicle=[d.get('make'),d.get('model')].filter(Boolean).join(' '),summary=$('[data-summary]');if(summary)summary.innerHTML=[['Fahrzeug',vehicle+' · '+d.get('plate')],['Kilometerstand',d.get('km')+' km'],['Anliegen',issue||'Sonstiges'],['Wunschtermin',d.get('date')+' · '+d.get('time')],['Mobilität',d.get('mobility')],['Kontakt',d.get('name')+' · '+d.get('email')]].map(([a,b])=>'<div><span>'+esc(a)+'</span><b>'+esc(String(b))+'</b></div>').join('');const requests=$('[data-requests]');if(requests){const p=document.createElement('p');p.innerHTML='<b>'+esc(String(d.get('name')||'Neue Anfrage'))+'</b><span>'+esc(vehicle)+' · '+esc(issue||'Anfrage')+'</span>';requests.prepend(p);const c=$('[data-count]');if(c)c.textContent=String(Number(c.textContent||0)+1)}show(4);note('Demo-Anfrage im Cockpit ergänzt.')});$('[data-restart]')?.addEventListener('click',()=>{form.reset();issue='';$$('.issues button').forEach(x=>x.classList.remove('active'));show(0)});show(0)}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const statusForm=$('[data-status-form]'),vehicle=$('[data-vehicle]'),badge=$('[data-badge]'),approval=$('[data-approval]'),statusErr=$('[data-status-error]');const orders={'A-1042':{pin:'4812',vehicle:'BMW 320d · SM-MW 320',status:'Wartet auf Freigabe',approval:true},'A-1045':{pin:'9911',vehicle:'VW Golf VII · WAK-GH 17',status:'Abholbereit',approval:false}};statusForm?.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(statusForm),key=String(d.get('order')||'').trim().toUpperCase(),pin=String(d.get('pin')||'').trim(),o=orders[key];if(!o||o.pin!==pin){statusErr.textContent='Demo-Auftrag nicht gefunden. Nutzen Sie A-1042 / 4812 oder A-1045 / 9911.';return}statusErr.textContent='';vehicle.textContent=o.vehicle;badge.textContent=o.status;badge.style.background=o.approval?'#fff1dc':'#e5f5ed';badge.style.color=o.approval?'#a65c0e':'#187b52';approval.hidden=!o.approval});
$('[data-approve]')?.addEventListener('click',e=>{e.currentTarget.disabled=true;e.currentTarget.textContent='Freigegeben ✓';badge.textContent='Freigegeben · in Planung';badge.style.background='#e5f5ed';badge.style.color='#187b52';$('[data-approval-note]').textContent='Demo: Freigabe lokal dargestellt, nichts gespeichert.';$('[data-jobstatus]').textContent='Freigegeben';$('[data-freigaben]').textContent='1';note('Zusatzarbeit wurde in der Demo freigegeben.')});$('[data-callback]')?.addEventListener('click',()=>{ $('[data-approval-note]').textContent='Rückrufwunsch vorgemerkt · keine echte Nachricht versendet.';note('Rückrufwunsch vorgemerkt.')});
const dlg=$('[data-dialog]');function open(){if(!dlg)return;if(dlg.showModal)dlg.showModal();else dlg.setAttribute('open','')}$$('[data-dashboard]').forEach(b=>b.addEventListener('click',open));$('[data-close]')?.addEventListener('click',()=>dlg?.close());dlg?.addEventListener('click',e=>{if(e.target===dlg)dlg.close()});$$('[data-tab]').forEach(b=>b.addEventListener('click',()=>{$$('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));$$('[data-panel]').forEach(x=>x.classList.toggle('active',x.dataset.panel===b.dataset.tab))}));
const date=$('input[name="date"]');if(date){const d=new Date(),min=new Date();d.setDate(d.getDate()+2);date.min=min.toISOString().slice(0,10);date.value=d.toISOString().slice(0,10)}
})();